version: '3'

services:
  database:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.16-focal
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ./db-data/:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - 8081:80
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'

  wordpress:
    depends_on:
      - database
    image: wordpress:6.4.1-php8.2-apache
    restart: unless-stopped
    ports:
      - 8080:80
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_NAME: '${MYSQL_DATABASE}'
      WORDPRESS_DB_USER: '${MYSQL_USER}'
      WORDPRESS_DB_PASSWORD: '${MYSQL_PASSWORD}'
      WORDPRESS_DEBUG: '${WORDPRESS_DEBUG}'
      WORDPRESS_CONFIG_EXTRA: define('FS_METHOD', 'direct');
      VITE_DEV_SERVER_ADDRESS: '${VITE_DEV_SERVER_ADDRESS}'
    volumes:
      - ./wp-content/:/var/www/html/wp-content

volumes:
  db-data: {}
  wp-uploads: {}
  wp-plugins: {}
